version: '3.8'
services:
  mythril:
    image: mythril/myth
    restart: always
    command: sleep 100000
    volumes: 
      - .:/tmp
  maincore:
    image: trailofbits/eth-security-toolbox
    restart: always
    command: sleep 100000
    volumes: 
      - .:/tmp      
volumes:
  db:
    driver: local

